//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_dataEntities : DbContext
    {
        public db_dataEntities()
            : base("name=db_dataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tbl_detail_order> tbl_detail_order { get; set; }
        public DbSet<tbl_menu> tbl_menu { get; set; }
        public DbSet<tbl_order> tbl_order { get; set; }
        public DbSet<tbl_pembayaran> tbl_pembayaran { get; set; }
        public DbSet<tbl_user> tbl_user { get; set; }
    }
}
